name: build_master

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-master:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull TexLive container
        run: docker pull texlive/texlive:latest

      - name: Run build in container
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace texlive/texlive:latest \
          bash -c "python make_master_monolithic.py; rm ./master/master.aux ./master/master.log ./master/master.out"

      - name: Deploy PDF to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./master
